POPULATION_SIZE = 6
MAX_STRESS = 20000
SAVE_TO_CSV_EVERY_N = 4
TIME_LIMIT = 15
GENERATION_LIMIT = 30
SAVE_PARENTS = True
SAVE_TEMP_FILES = True
BACKUP_TO_CSV = True
RESTART_AFTER_ERROR = False
# INACTIVITY LIMIT = 1000


